#!/bin/bash

DOTFILEDIR=$(cd $(dirname $0);pwd)

function link_conf() {
	source=$1
	target=$2
	sudo=$3

	[ -d $(dirname $target) ] || mkdir -p $(dirname $target)
	[ -e $target ] && return

	if [ -z $sudo ]; then
		echo "Installing ${target}"
		ln -s $source $target
	else
		sudo -k
		echo "Installing (sudo) ${target}"
		sudo ln -s $source $target
	fi
}

function copy_conf() {
	source=$1
	target=$2
	sudo=$3

	[ -d $(dirname $target) ] || mkdir -p $(dirname $target)
	[ -e $target ] && return

	if [ -z $sudo ]; then
		echo "Installing ${target}"
		cp $source $target
	else
		sudo -k
		echo "Installing (sudo) ${target}"
		sudo cp $source $target
	fi
}

function install_module() {
    module=$1
    install_script="${DOTFILEDIR}/${module}/install"

    if [ -x "${install_script}" ]; then
        source "${install_script}" $(dirname "${install_script}")
    else
        echo "No such module: ${module}"
        exit 1
    fi
}

function all_modules() {
    for dir in ${DOTFILEDIR}/*/install; do
        basename $(dirname $dir)
    done
}

if [ ! -z "$1" ]; then
    modules="${@}"
else
    modules="$(all_modules)"
fi

for module in ${modules}; do
    install_module "${module}"
done