# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt"
  config.vm.provider :libvirt do |domain|
    domain.cpu_mode = 'host-passthrough'
  end
  config.landrush.enabled = true
  config.landrush.tld = 'vagrant.dev'
  config.landrush.guest_redirect_dns = false
  config.landrush.host_redirect_dns = false
end
