auto_sync = false
update_check = false

secrets_filter = true
style = "compact"

inline_height = 15
show_preview = true
show_help = false

enter_accept = false

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "aws",
  "brew",
  "cargo",
  "go",
  "git",
  "k",
  "kubectl",
  "mvn",
  "npm",
  "pm",
  "podman",
  "terraform",
]

# Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]
