[[ -d $HOME/bin ]] && export PATH="$HOME/bin:$PATH"
xset -b
wmname Awesome
[[ -f $HOME/.Xresources ]] && xrdb -merge ~/.Xresources

if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f" && echo "$f"
    done
fi

nm-applet &

exec dbus-launch awesome
