ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [[ ! -e "${ZINIT_HOME}" ]]; then
    read -q "?$ZINIT_HOME does not exist, do you want to install it? " || return -1
    print '\ninstalling zinit'
    mkdir -p "$(dirname $ZINIT_HOME)"
    git clone --depth 1 https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

function __ensure_package_is_installed() {
    local command="$1"
    local package="${2:-${command}}"

    case "$(uname -s)" in
        Darwin)
            if ! [[ -d "/opt/homebrew/opt/${package}" ]]; then
                print "The ${package} homebrew package is not installed.\n"
                read -q "?Do you want to install it? " || return -1
                print ''
                brew install "${package}"
            fi
            ;;
        *)
            if ! (( $+commands[${command}] )); then
                print "The ${command} command was not found on your path.\n"
                print "Please install the ${package} package manually.\n"
            fi
            ;;
    esac
}

for script in "${HOME}"/.zsh.d/{bootstrap,,tooling,env}/*.zsh; do
    source $script
done

source "${HOME}/.zshrc_local"
